
export const sampleDocumentTypesAGROS = [
    "Avvisning av utbetalingsanmodning - Drenering",
    "Delutbetaling av tilskudd - Drenering",
    "Delutbetaling av tilskudd - SMIL",
    "Delutbetaling av tilskudd - Tiltak i beiteområder",
    "Delutbetaling av tilskudd - Utvalgte kulturlandskap",
    "Ettersending - Drenering",
    "Ettersending - SMIL",
    "Ettersending - Sykdomsavløsning",
    "Forskuddsbetaling - Produksjonssvikt",
    "Melding - Produksjonssvikt (melding)",
    "Saksavslutning - Drenering",
    "Saksavslutning - SMIL",
    "Saksavslutning - ukl",
    "Sluttutbetaling av tilskudd - Drenering",
    "Sluttutbetaling av tilskudd - kulturlandskap",
    "Sluttutbetaling av tilskudd - SMIL",
    "Sluttutbetaling av tilskudd - Tiltak i beiteområder",
    "Søknad om tilskudd - beit",
    "Søknad - Drenering",
    "Søknad - SMIL",
    "Søknad om tilskudd - Drenering",
    "Søknad om tilskudd - Produksjonssvikt",
    "Søknad om tilskudd - SMIL",
    "Søknad om tilskudd - sykavl",
    "Søknad - Sykdomsavløsning",
    "Søknad om tilskudd - Sykdomsavløsning",
    "Søknad om tilskudd - tiltak i beiteområde",
    "Søknad om tilskudd - ukl",
    "Utbetalingsanmodning - Drenering",
    "Utbetalingsanmodning - kulturlandskap",
    "Utbetalingsanmodning - SMIL",
    "Utbetalingsanmodning - Tiltak i beiteområde",
    "Varsel om frist for å gjennomføre og rapportere - beit",
    "Varsel om frist for å gjennomføre og rapportere - Drenering",
    "Varsel om frist for å gjennomføre og rapportere - SMIL",
    "Varsel om frist for å gjennomføre og rapportere - tiltak i beiteområde",
    "Varsel om frist for å gjennomføre og rapportere - ukl",
    "Vedlegg - Drenering",
    "Vedlegg - Produksjonssvikt (melding)",
    "Vedlegg - SMIL",
    "Vedlegg - Sykdomsavløsning",
    "Vedlegg - Tiltak i beiteområde",
    "Vedlegg - Utvalgte kulturlandskap",
    "Vedtak - Drenering",
    "Vedtak - SMIL",
    "Vedtak - Sykdomsavløsning",
    "Vedtak om avslag på søknad om tilskudd til drenering av jordbruksjord",
    "Vedtak om tilskudd til tiltak I beiteområder",
    "Vedtak til søknad om tilskudd - Produksjonssvikt",
    "Vedtak til søknad om tilskudd - SMIL",
    "Vedtak til søknad om tilskudd - sykavl",
    "Vedtak til søknad om tilskudd - Sykdomsavløsning",
    "Vedtak til søknad om tilskudd - tiltak i beiteområde",
    "Vedtak til søknad om tilskudd - ukl",
    "Vedtak til søknad om tilskudd - Utvalgte kulturlandskap",
   // Legg til flere dokumenttyper...
 ];
 
 export const sampleDocumentTypesEStil = [
    "Søknad for RMP og OBB",
    "Søknadskvittering for RMP og OBB",
    "Tilskuddsbrev for RMP og OBB",
    "Vedlegg for RMP og OBB",
    "Vedtak om utbetaling av regionalt miljøtilskudd søknadsomgang",
    // Legg til flere dokumenttyper...
 ];

 export const sampleDocumentTypesPT = [
   "Faktura",
   "Notat produksjons- og avløsertilskudd",
   "Søknad produksjons- og avløsertilskudd",
   "Vedlegg produksjons- og avløsertilskudd",
   "Vedtak produksjons- og avløsertilskudd",
   // Legg til flere dokumenttyper...
];

export const sampleDocumentTypesØKS = [
   "Søknad hogst i marka",
   "Søknad om drifstilskudd",
   "Søknad om utbetaling av udekka",
   "Søknad skogfond og tilskudd",
   "Vedtak for driftstilskudd (avslått)",
   "Vedtak skogfond (udekka investering)",
   "Vedtak skogfond og tilskudd (avslått)",
   "Vedtak skogfond og tilskudd (godkjent)",
   "Vedtaksbrev for driftstilskudd",
   "Vedtaksbrev for driftstilskudd storm",
   "Vedtaksbrev for driftstilskudd storm (avslått)",
   "Vedtaksbrev for hogstmelding",
   "Vedtaksbrev for miljøtilskudd",
   "Vedtaksbrev for tilbakemelding",
   // Legg til flere dokumenttyper...
];